name: Deploy

on:
  release:
    types: [published]
    paths:
      - 'task-manager/*'
      - 'web-server/*'
      - 'notes-app/*'
      - 'chat-app/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Get updated files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            task-manager/**
            web-server/**
            notes-app/**
            chat-app/**
      - name: Deploy Task-manager app
        if: contains(steps.changed-files-specific.outputs.all_changed_and_modified_files, 'task-manager')
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.TASK_APP_TOKEN }}
        working-directory: ./task-manager
      - name: Deploy web-server app
        if: contains(steps.changed-files-specific.outputs.all_changed_and_modified_files, 'web-server')
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.WEATHER_APP_TOKEN }}
        working-directory: ./web-server
      - name: Deploy chat app
        if: contains(steps.changed-files-specific.outputs.all_changed_and_modified_files, 'chat-app')
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.CHAT_APP_TOKEN }}
        working-directory: ./chat-app
